Com.EzTender.WebApp/Controllers/CompaniesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Com.BudgetMetal.Common;
using Com.BudgetMetal.Services.Company;
using Com.BudgetMetal.Services.Roles;
using Com.BudgetMetal.ViewModels.Company;
using Com.EazyTender.WebApp.Configurations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;
using Com.BudgetMetal.Services.Rating;

namespace Com.EzTender.WebApp.Controllers
{
    public class CompaniesController : Controller
    {
        private readonly ICompanyService svs;
        private readonly AppSettings _appSettings;
        private readonly IRoleService roleService;
        private readonly IRatingService ratingService;

        public CompaniesController(ICompanyService svs, IOptions<AppSettings> appSettings, IRoleService roleService, IRatingService ratingService)
        {
            this.svs = svs;
            this._appSettings = appSettings.Value;
            this.roleService = roleService;
            this.ratingService = ratingService;
        }
        
        // GET: Companies
        public async Task<ActionResult> Index(string keyword, int page, int totalRecords)
        {
            var result = await svs.GetCompanySupplierList(keyword, page, _appSettings.TotalRecordPerPage);
            ViewData["keyword"] = keyword;

            return View(result);
        }

        // GET: PreferSuppliers
        public async Task<ActionResult> PreferSuppliers(int page, string keyword)
        {
            var company_Id = HttpContext.Session.GetString("Company_Id");
            int id = Convert.ToInt32(company_Id);
            var result = await svs.GetSupplierByCompany(id, page, keyword);
            ViewData["keyword"] = keyword;
            return View(result);
        }

        // GET: Companies/Details/5
        public async Task<IActionResult> Profile()
        {
            int id = Convert.ToInt32(HttpContext.Session.GetString("Company_Id"));
            var User_Id = HttpContext.Session.GetString("User_Id");
            var userRoles = JsonConvert.DeserializeObject<List<BudgetMetal.ViewModels.Role.VmRoleItem>>(HttpContext.Session.GetString("SelectedRoles"));
            bool isCompanyAdmin = false;
            if (userRoles.Where(e => e.Id == Constants.C_Admin_Role).ToList().Count > 0)
            {
                isCompanyAdmin = true;
            }
            ViewData["isAdmin"] = isCompanyAdmin;
            VmCompanyItem item = await svs.GetCompanyProfileById(id);

            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        public async Task<IActionResult> Details(int id)
        {
            VmCompanyItem item = await svs.GetCompanyProfileById(id);

            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // GET: Companies/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Companies/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Companies/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Companies/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Companies/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Companies/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpPost]
        public async Task<JsonResult> EditCompanyAbout(int CompanyId, string About)
        {
            string updatedBy = HttpContext.Session.GetString("EmailAddress");
            var result = await svs.EditCompanyAbout(CompanyId, About, updatedBy);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpPost]
        public async Task<JsonResult> EditCompanyAddress(int CompanyId, string Address)
        {
            string updatedBy = HttpContext.Session.GetString("EmailAddress");
            var result = await svs.EditCompanyAddress(CompanyId, Address, updatedBy);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpPost]
        public async Task<JsonResult> EditCompanyUser(int CompanyId, int UserId, string IsConfirmStatus)
        {
            string updatedBy = HttpContext.Session.GetString("EmailAddress");
            bool isActiveStatus = (IsConfirmStatus == "Active") ? false : true;
            var result = await svs.EditCompanyUser(CompanyId, UserId, isActiveStatus, updatedBy);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpGet]
        public async Task<JsonResult> GetuserRole(string RoleType)
        {
            var result = await roleService.GetActiveRoles(RoleType);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpPost]
        public async Task<JsonResult> EditCompanyUserRole(int CompanyId, int UserId, string[] userRole)
        {
            string updatedBy = HttpContext.Session.GetString("EmailAddress");
            
            var result = await svs.EditCompanyUserRole(CompanyId, UserId, userRole, updatedBy);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpGet]
        public async Task<JsonResult> GetRatingData(int page,int companyId)
        {
            //var Company_Id = HttpContext.Session.GetString("Company_Id");
            //int companyId = (Company_Id != null) ? int.Parse(Company_Id) : 0;
            var result = await ratingService.GetRatingData(page, 10, companyId, 0, "");

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }
    }
}

Com.EzTender.WebApp/Controllers/SupplierController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Com.BudgetMetal.Services.Company;
using Com.BudgetMetal.Services.RFQ;
using Com.BudgetMetal.ViewModels.Company;
using Com.EazyTender.WebApp.Configurations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace Com.EzTender.WebApp.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly ICompanyService svs;
        private readonly AppSettings _appSettings;
        private readonly IRFQService rfqService;

        public SuppliersController(ICompanyService svs, IOptions<AppSettings> appSettings, IRFQService rfqService)
        {
            this.svs = svs;
            this._appSettings = appSettings.Value;
            this.rfqService = rfqService;
        }


        //public ActionResult PublicRfqByCompany(int id)
        //{
        //    ViewBag.Company_Id = id;

        //    return View();
        //}
        // GET: Suppliers
        public async Task<ActionResult> Index(string keyword, int page, int totalRecords)
        {
            var result = await svs.GetCompanySupplierList(keyword, page, _appSettings.TotalRecordPerPage);

            return View(result);
        }

        // GET: Suppliers/Details/5        
        public async Task<IActionResult> Details(int id)
        {
            VmCompanyItem item = await svs.GetCompanyById(id);
            
            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // GET: Suppliers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Suppliers/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Suppliers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Suppliers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Suppliers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<JsonResult> GetSupplier(int page, string status, string Company_Id, string skeyword)
        {
            var result = await svs.GetCompanySupplierList(skeyword, page, 3);
            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        //[HttpGet]
        //public async Task<JsonResult> GetPublicRFQByCompany(int page, int Company_Id, string status, string skeyword)
        //{
        //    //var company_Id = HttpContext.Session.GetString("Company_Id");
        //    var result = await rfqService.GetPublicRfqByCompany(page, Company_Id, 2, Convert.ToInt32(status),
        //        skeyword == null ? "" : skeyword);

        //    return new JsonResult(result, new JsonSerializerSettings()
        //    {
        //        ReferenceLoopHandling = ReferenceLoopHandling.Ignore
        //    });
        //}
    }
}

Com.EzTender.WebApp/Views/Suppliers/Details.cshtml
@model Com.BudgetMetal.ViewModels.Company.VmCompanyItem
@using System.Linq;

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="block-header">
    <h2>@Html.DisplayFor(model => model.Name)</h2>
</div>

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                <h2>
                    About
                </h2>
                <br />
                <small>@Html.DisplayFor(model => model.About)</small>
                <ul class="header-dropdown m-r--5">
                    <li class="dropdown">
                        <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                            <i class="material-icons">edit</i>
                        </a>
                        <ul class="dropdown-menu pull-right">
                            <li><a href="javascript:void(0);" class=" waves-effect waves-block">Edit</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>
<div class="row clearfix">
    <!-- Linked Items -->
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="header">
                UEN No. : <b>@Html.DisplayFor(model => model.RegNo)</b>
            </div>
            <div class="header">
                    Address: <b>@Html.DisplayFor(model => model.Address)</b>
            </div>
        </div>
    </div>
</div>

Com.EzTender.WebApp/Views/Suppliers/Index.cshtml
@model Com.BudgetMetal.ViewModels.Company.VmCompanyPage
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/_Empty_Layout.cshtml";
}



<!-- Basic Alerts -->
@*<div class="row">
    <div class="col-sm-6">
        <div class="btn-group" role="group" aria-label="Justified button group">
            <button id="btn_tender_open" class="btn btn-default waves-effect btnStatus" data-item-id="100032" type="button">Open</button>
            <button id="btn_tender_close" class="btn btn-primary waves-effect btnStatus" data-item-id="100033" type="button">Closed</button>
        </div>
    </div>
    <div class="col-sm-6"></div>
</div>*@

<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            <div class="body">
                <div class="row">
                    <div class="col-sm-11">
                        <div class="form-group">
                            <div class="form-line">
                                <input type="text" id="keyword" name="keyword" class="form-control" placeholder="<Company Name>" value="">
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-1">
                        <input type="hidden" name="statusId" id="statusId" value="0" />

                        <button type="button" class="btn bg-indigo pull-right" id="btnSearch"> Search </button>
                    </div>
                </div>
                <div class="row" id="CompanyList"></div>
                <div class="row">
                    <div class="pagination" style="padding:10px;">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<script>
    $(function () {
        //loadPublicCompanyList(1);
    });

    $("button.btnStatus").on({
        click: function () {
            $('.btnStatus').removeClass("btn-default").removeClass("btn-primary").addClass("btn-primary");
            $(this).removeClass("btn-default").removeClass("btn-primary").addClass("btn-default");
            var statusId = $(this).data("item-id");
            $('#statusId').val(statusId);
            $('#CompanyList').empty();
            loadPublicCompanyList(1);
        }
    });

    $("#btnSearch").on({
        click: function () {
            $('#CompanyList').empty();
            loadPublicCompanyList(1);
        }
    });

    $("#keyword").keyup(function (event) {
        if (event.keyCode === 13) {
            $("#btnSearch").click();
        }
    });

    function loadPublicCompanyList(page) {
        var keyword = $('#keyword').val();
        var statusId = $('#statusId').val();
        var company = $('#Company_Id').val();
        var ajaxurl = "/Suppliers/GetSupplier?page=" + page + "&status=100032&Company_Id=1&skeyword=" + encodeURIComponent(keyword);
        $.ajax({
            url: ajaxurl,
            data: { page: page, status: statusId, Company_Id: company, skeyword: keyword},
            dataType: 'json',
            success: function (response) {
                var obj = response.Result.Records;
                for (var k in obj) {
                    var item = obj[k];
                    $('#CompanyList').append(
                        "<div class='clearfix' style='padding-left: 20px; padding-right: 20px;'> " +
                        "<div class='row'> " +
                        "<div class='col-sm-6'>Reg No. " + item.RegNo + "</div> " +
                        
                         "</div> " +
                        "<div class='row'> " +
                        "<div class='col-sm-12'><b>Name. " + item.Name + "</b></div> " +
                         "</div> " +
                            "<div class='row'> " +
                        "<div class='col-sm-4'>About: " + item.About + "</div> " +
                        " </div> " +
                        "<div class='row'> " +
                                "<div class='col-sm-4'>Address: " + item.Address + "</div> " +
                        " </div> " +
                        " <hr/> "
                    );

                }
                var totalRecord = response.Result.TotalRecords;

                var openTab = $('#btn_tender_open');
                var openTabClass = openTab.prop('class');
                if (openTabClass.includes('btn-default')) {

                    openTab.html("Open (" + totalRecord + ")")
                }

                var closeTab = $('#btn_tender_close');
                var closeTabClass = closeTab.prop('class');
                if (closeTabClass.includes('btn-default')) {

                    closeTab.html("Close (" + totalRecord + ")")
                }

                var totalpage = response.Result.TotalPage;
                var currentpage = response.Result.CurrentPage;
                if (totalpage > currentpage) {
                    $(".pagination").empty();
                    $(".pagination").append(" <a class='btn btn-md btn-default' OnClick='loadPublicCompanyList(" + response.Result.NextPage + ")'> Load More </a> ");
                } else {
                    $(".pagination").empty();
                }
            },
            error: function (response) {
                alert(response)
            }
        });
    }
</script>

@*<div class="card">
        <div class="header">
            <br />
            <div class="row">
                @using (Html.BeginForm("Index", "Companies", FormMethod.Get))
                {
                    <div class="col-sm-5">
                        @Html.TextBox("keyword",
                         null,
                         new {
                             id = "search_key",
                             @class = "form-control"
                         })
                    </div>
                    <div class="col-sm-1">
                        <input class="btn btn-info" type="submit" value="Search" />
                    </div>
                }
            </div>
        </div>
        <br />
        <table class="table table-hover">
            <thead>
                <tr>
                    <th> # </th>
                    <th> Name </th>
                    <th> Address </th>
                    <th> Domain </th>
                    <th> Registration No. </th>
                    <th> About </th>
                    <th> IsVerified </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                    foreach (var item in Model.Result.Records)
                    {
                        string checkedStatus = (item.IsVerified) ? "checked" : "";
                        <tr>
                            <td> @counter </td>
                            <td> @item.Name </td>
                            <td> @item.Address </td>
                            <td> @item.Domain </td>
                            <td> @item.RegNo </td>
                            <td> @item.About </td>
                            <td> <input type="checkbox" id="@counter" class="chk-col-pink" @checkedStatus disabled> <label for="@counter"></label> </td>
                            <td> <a type="button" class="btn btn-warning" href='@Url.Action("Details","Suppliers",new { id= item.Id })'>View</a></td>
                        </tr>
                        counter = counter + 1;
                    }
                }
            </tbody>
        </table>
        <div class="row">
            <div class="col-sm-12">
                <div class="pagination pull-right" style="padding:10px;">
                    @{
                        int currentPage = Model.Result.CurrentPage;
                        int totalPage = Model.Result.TotalPage;
                        int previousPage = Model.Result.PreviousPage;
                        int nextPage = Model.Result.NextPage;

                        int startPage = currentPage - 5;
                        int endPage = currentPage + 4;

                        if (startPage <= 0)
                        {
                            endPage -= (startPage - 1);
                            startPage = 1;
                        }
                        if (endPage > totalPage)
                        {
                            endPage = totalPage;
                            if (endPage > 10)
                            {
                                startPage = endPage - 9;
                            }
                        }

                        @if (endPage > 1)
                        {
                            <ul class="pagination">
                                @if (currentPage > 1)
                                {
                                    <li>
                                        <a class='btn btn-md btn-primary' href="~/Companies">First</a>
                                    </li>
                                    <li>
                                        <a class='btn btn-md btn-primary' href="?page=@(currentPage - 1)">Previous</a>
                                    </li>
                                }

                                @for (int page = startPage; page <= endPage; page++)
                                {
                                    <li class="@(page == currentPage ? "active" : "")">
                                        <a class='btn btn-md btn-primary' href="?page=@(page)"> @(page) </a>
                                    </li>
                                }

                                @if (currentPage < totalPage)
                                {
                                    <li>
                                        <a class='btn btn-md btn-primary' href="?page=@(currentPage + 1)">Next</a>
                                    </li>
                                    <li>
                                        <a class='btn btn-md btn-primary' href="?page=@(totalPage)">Last</a>
                                    </li>
                                }
                            </ul>
                        }
                    }
                </div>
            </div>
        </div>
    </div>*@