Com.EazyTender_Admin/Controllers/DocumentsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Com.BudgetMetal.Services.Document;
using Com.BudgetMetal.ViewModels.Document;
using Com.EazyTender_Admin.Configurations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Com.EazyTender_Admin.Controllers
{
    public class DocumentsController : Controller
    {
        private readonly IDocumentService svs;
        private readonly AppSettings _appSettings;

        public DocumentsController(IDocumentService svs, IOptions<AppSettings> appSettings)
        {
            this.svs = svs;
            this._appSettings = appSettings.Value;
        }

        // GET: Document
        public async Task<ActionResult> Index(string keyword, int page, int totalRecords)
        {
            var result = await svs.GetDocumentByPage(keyword, page, _appSettings.TotalRecordPerPage);

            return View(result);
        }

        // GET: Document/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Document/Create
        public async Task<ActionResult> Create()
        {
            var obj = await svs.GetFormObject();
            return View(obj);
        }

        // POST: Document/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(VmDocumentItem vmItem)
        {
            var result = svs.Insert(vmItem);

            if (result.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(vmItem);
            }
        }

        // GET: Document/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            var obj = await svs.GetDocumentById(id);
            return View(obj);
        }

        // POST: Document/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, VmDocumentItem vmItem)
        {
            if (id != vmItem.Id)
            {
                return NotFound();
            }

            var result = await svs.Update(vmItem);

            if (result.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(vmItem);
            }
        }

        // GET: Document/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            await svs.Delete(id);
            return RedirectToAction(nameof(Index));
        }

        // POST: Document/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
                await svs.Delete(id);
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Com.EazyTender_Admin/Views/Documents/Create.cshtml
@model Com.BudgetMetal.ViewModels.Document.VmDocumentItem

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>VmDocumentItem</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPersonName" class="control-label">Contact Person</label>
                <input asp-for="ContactPersonName" class="form-control" />
                <span asp-validation-for="ContactPersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentNo" class="control-label">Document No.</label>
                <input asp-for="DocumentNo" class="form-control" />
                <span asp-validation-for="DocumentNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubmissionDate" class="control-label"></label>
                <input asp-for="SubmissionDate" class="form-control" />
                <span asp-validation-for="SubmissionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company_Id" class="control-label">Company</label>
                <select asp-for="Company_Id" asp-items="@(new SelectList(Model.CompanyList, "Id", "Name"))" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="Company_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentStatus_Id" class="control-label">Document Status</label>
                <select asp-for="DocumentStatus_Id" asp-items="@(new SelectList(Model.DocumentStatusList, "Id", "Name"))" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="DocumentStatus_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentType_Id" class="control-label">Document Type</label>
                <select asp-for="DocumentType_Id" asp-items="@(new SelectList(Model.DocumentTypeList, "Id", "Name"))" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="DocumentType_Id" class="text-danger"></span>
            </div>
            <div class="form-group" hidden="hidden">
                <label asp-for="CreatedBy" class="control-label"></label>
                <input asp-for="CreatedBy" class="form-control" />
                <span asp-validation-for="CreatedBy" class="text-danger"></span>
            </div>
            <input type="hidden" asp-for="CreatedBy" class="form-control" />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Com.EazyTender_Admin/Views/Documents/Edit.cshtml
@model Com.BudgetMetal.ViewModels.Document.VmDocumentItem

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h3>VmDocumentItem</h3>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="ContactPersonName" class="control-label">Contact Person</label>
                <input asp-for="ContactPersonName" class="form-control" />
                <span asp-validation-for="ContactPersonName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentNo" class="control-label">Document No</label>
                <input asp-for="DocumentNo" class="form-control" />
                <span asp-validation-for="DocumentNo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SubmissionDate" class="control-label">Submission Date</label>
                <input asp-for="SubmissionDate" class="form-control" />
                <span asp-validation-for="SubmissionDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Company_Id" class="control-label">Company</label>
                <select asp-for="Company_Id" asp-items="@(new SelectList(Model.CompanyList, "Id", "Name"))" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="Company_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentStatus_Id" class="control-label">Document Status</label>
                <select asp-for="DocumentStatus_Id" asp-items="@(new SelectList(Model.DocumentStatusList, "Id", "Name"))" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="DocumentStatus_Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DocumentType_Id" class="control-label">Document Type</label>
                <select asp-for="DocumentType_Id" asp-items="@(new SelectList(Model.DocumentTypeList, "Id", "Name"))" class="form-control">
                    <option>Please select one</option>
                </select>
                <span asp-validation-for="DocumentType_Id" class="text-danger"></span>
            </div>
            <div class="form-group" hidden="hidden">
                <label asp-for="Id" class="control-label"></label>
                <input asp-for="Id" class="form-control" />
                <span asp-validation-for="Id" class="text-danger"></span>
            </div>
            <div class="form-group">
                <div class="checkbox">
                    <label>
                        <input asp-for="IsActive" /> @Html.DisplayNameFor(model => model.IsActive)
                    </label>
                </div>
            </div>
            <input type="hidden" asp-for="UpdatedBy" class="form-control" />
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Com.EazyTender_Admin/Views/Documents/Index.cshtml
@model Com.BudgetMetal.ViewModels.Document.VmDocumentPage

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<h3>Document</h3>
<div class="card">
    <div class="row"></div>
    <div class="header">
        <div class="row">
            @using (Html.BeginForm("Index", "Documents", FormMethod.Get))
            {
                <div class="col-sm-5">
                    @Html.TextBox("Keyword",
         null,
         new {
             id = "search_key",
             @class = "form-control"
         })
                </div>
                <div class="col-sm-1">
                    <input class="btn btn-info" type="submit" value="Search" />
                </div>
            }
        </div>
    </div>
    <br />
    <div class="body-content">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        #
                    </th>
                    <th>
                        Title
                    </th>
                    <th>
                        Contact Person
                    </th>
                    <th>
                        Document No.
                    </th>
                    <th>
                        SubmissionDate
                    </th>
                    <th>
                        Company
                    </th>
                    <th>
                        Status
                    </th>
                    <th>
                        Type
                    </th>
                    <th><a asp-action="Create">Create New</a></th>
                </tr>
            </thead>
            <tbody>
                @{
                    int counter = 1;
                    foreach (var item in Model.Result.Records)
                    {
                        <tr>
                            <td> @counter </td>
                            <td> @item.Title </td>
                            <td> @item.ContactPersonName </td>
                            <td> @item.DocumentNo </td>
                            <td> @item.SubmissionDate </td>
                            <td> @(item.Company == null ? "" : item.Company.Name)</td>
                            <td> @(item.DocumentStatus == null ? "" : item.DocumentStatus.Name)</td>
                            <td> @(item.DocumentType == null ? "" : item.DocumentType.Name)</td>
                            <td hidden="hidden"> @item.Id </td>
                            <td>
                                <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                                <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                            </td>
                        </tr>
                        counter++;
                    }
                }
            </tbody>
        </table>

        <div class="row">
            <div class="col-sm-12">
                <div class="pagination pull-right" style="padding:10px;">
                    @{
                        int currentPage = Model.Result.CurrentPage;
                        int totalPage = Model.Result.TotalPage;
                        int previousPage = Model.Result.PreviousPage;
                        int nextPage = Model.Result.NextPage;

                        int startPage = currentPage - 5;
                        int endPage = currentPage + 4;

                        if (startPage <= 0)
                        {
                            endPage -= (startPage - 1);
                            startPage = 1;
                        }
                        if (endPage > totalPage)
                        {
                            endPage = totalPage;
                            if (endPage > 10)
                            {
                                startPage = endPage - 9;
                            }
                        }

                        @if (endPage > 1)
                        {
                            <ul class="pagination">
                                @if (currentPage > 1)
                                {
                                    <li>
                                        <a class='btn btn-md btn-primary' href="~/Documents">First</a>
                                    </li>
                                    <li>
                                        <a class='btn btn-md btn-primary' href="?page=@(currentPage - 1)">Previous</a>
                                    </li>
                                }

                                @for (int page = startPage; page <= endPage; page++)
                                {
                                    <li class="@(page == currentPage ? "active" : "")">
                                        <a class='btn btn-md btn-primary' href="?page=@(page)"> @(page) </a>
                                    </li>
                                }

                                @if (currentPage < totalPage)
                                {
                                    <li>
                                        <a class='btn btn-md btn-primary' href="?page=@(currentPage + 1)">Next</a>
                                    </li>
                                    <li>
                                        <a class='btn btn-md btn-primary' href="?page=@(totalPage)">Last</a>
                                    </li>
                                }
                            </ul>
                        }
                    }
                </div>
            </div>
        </div>
    </div>
</div>