Com.EzTender.PublicPortal/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;
using Com.BudgetMetal.Services.RFQ;
using Com.BudgetMetal.Services.Industries;
using Configurations;
using Com.BudgetMetal.Services.Company;
using Com.BudgetMetal.Services.ServiceTags;
using Com.BudgetMetal.Services.Users;
using Com.BudgetMetal.Services.Attachment;
using Microsoft.Extensions.Options;
using Com.BudgetMetal.ViewModels.User;
using System.Threading.Tasks;
using System;
using Com.BudgetMetal.Common;
using Newtonsoft.Json;
using System.Linq;
using Microsoft.AspNetCore.Http;
using Com.BudgetMetal.ViewModels.SupplierServiceTag;
using System.Collections.Generic;

// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace Com.EzTender.PublicPortal.Controllers
{
    public class RegistrationController : Controller
    {
        private readonly AppSettings _appSettings;
        private readonly IIndustryService industryService;
        private readonly ICompanyService companyService;
        private readonly IServiceTagsService serviceTagsService;
        private readonly IUserService userService;

        public RegistrationController(IIndustryService industryService, 
                                      ICompanyService companyService, 
                                      IServiceTagsService serviceTagsService, 
                                      IUserService userService, 
                                      IOptions<AppSettings> appSettings)
        {
            this.industryService = industryService;
            this.companyService = companyService;
            this.serviceTagsService = serviceTagsService;
            this.userService = userService;
            this._appSettings = appSettings.Value;
        }

        // GET: /<controller>/
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(VmUserItem user)
        {
            string[] serviceTags;
            serviceTags = Request.Form["serviceTags"].ToArray();

            var result = await userService.Register(user, serviceTags);
            if (result.IsSuccess)
            {
                string mailBody = "";
                string confirmationLink = "";

                //var location = new Uri($"{Request.Scheme}://{Request.Host}{Request.Path}{Request.QueryString}");
                var location = new Uri($"{Request.Scheme}://{Request.Host}");
                var url = location.AbsoluteUri;
                string encodeEmail = user.EmailAddress.EncodeString(); // Convert.ToBase64String(Encoding.UTF8.GetBytes(user.EmailAddress));
                string token = _appSettings.App_Identity.Identity;
                //var byte_time = Encoding.UTF8.GetBytes(DateTime.Now.AddDays(2).ToString());
                string encodeTimeLimit = DateTime.Now.AddDays(2).ToString().EncodeString(); // Convert.ToBase64String(byte_time);
                confirmationLink = url + "Registration/ConfirmUser?token=" + token + "&e=" + encodeEmail + "&t=" + encodeTimeLimit;

                mailBody = "Please confirm your account by clicking the following link \n " + confirmationLink;
                SendingMail sm = new SendingMail();
                sm.SendMail(user.EmailAddress, "", "Confirmation for Registration", mailBody);
                return RedirectToAction("SuccessRegistration");
            }
            else
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<string> LoadServiceTags()
        {
            var resultIndustry = await industryService.GetActiveIndustries();

            var resultServiceTags = await serviceTagsService.GetActiveVmServiceTags();

            string returnString = "";
            if (resultIndustry != null && resultServiceTags != null)
            {
                foreach (var itemIndustry in resultIndustry)
                {
                    returnString = returnString + "<optgroup label='" + itemIndustry.Name + "'>";
                    var resultServiceTagsByIndustry = resultServiceTags.Where(e => e.Industry_Id == itemIndustry.Id).ToList();
                    foreach (var itemServiceTag in resultServiceTagsByIndustry)
                    {
                        returnString = returnString + "<option value='" + itemServiceTag.Id.ToString() + "'>" + itemServiceTag.Name + "</option>";
                    }

                    returnString = returnString + "</optgroup>";
                }
            }

            return returnString;
        }

        [HttpGet]
        public async Task<JsonResult> CheckEmail(string Email)
        {
            var result = await userService.CheckEmail(Email);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpGet]
        public async Task<JsonResult> CheckUEN(string RegNo)
        {
            var result = await companyService.GetCompanyByUEN(RegNo);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpGet]
        public async Task<JsonResult> GetServiceTagsByCompanyId(int companyId)
        {
            List<VmSupplierServiceTag> result = await companyService.GetCompanyServiceTagById(companyId);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpGet]
        public async Task<JsonResult> ResetPassword(string Email)
        {
            string newPassword = CreateRandomPassword(6);
            var result = await userService.ResetPassword(Email, newPassword);

            if (result.IsSuccess)
            {
                string mailBody = "";
                mailBody = "Your new password for EzyTender is " + newPassword;
                SendingMail sm = new SendingMail();
                sm.SendMail(Email, "", "Reset Password", mailBody);
            }

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        public string CreateRandomPassword(int PasswordLength)
        {
            string _allowedChars = "0123456789asdfghjklqwertyuiopzxcvbnm";
            Random randNum = new Random();
            char[] chars = new char[PasswordLength];
            int allowedCharCount = _allowedChars.Length;

            for (int i = 0; i < PasswordLength; i++)
            {
                chars[i] = _allowedChars[(int)((_allowedChars.Length) * randNum.NextDouble())];
            }
            return new string(chars);
        }

        // GET: User
        [HttpGet]
        public ActionResult ForgotPassword()
        {
            HttpContext.Session.SetString("WebAppUrl", _appSettings.App_Identity.WebAppUrl);
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> ConfirmUser()
        {
            HttpContext.Session.SetString("WebAppUrl", _appSettings.App_Identity.WebAppUrl);
            string token = _appSettings.App_Identity.Identity;
            string _token = Request.Query["token"];
            //HttpContext.Session.SetString("WebAppUrl", _appSettings.App_Identity.WebAppUrl);
            if (token == _token)
            {
                string email = Request.Query["e"];
                string timeLimit = Request.Query["t"];
                if (timeLimit != null && email != null)
                {
                    email = email.DecodeString(); // Encoding.UTF8.GetString(Convert.FromBase64String(email));
                    timeLimit = timeLimit.DecodeString(); // Encoding.UTF8.GetString(Convert.FromBase64String(timeLimit));

                    if (DateTime.Now < Convert.ToDateTime(timeLimit))
                    {
                        var result = await userService.ConfirmUserName(email);

                        if (result.IsSuccess)
                        {
                            TempData["IsSuccess"] = true;
                            TempData["Message"] = "You have successfully confirmed your account.";
                        }
                        else
                        {
                            TempData["IsSuccess"] = false;
                            TempData["Message"] = "Fail to confrim your account. " + result.MessageToUser;
                        }
                    }
                    else
                    {
                        TempData["IsSuccess"] = false;
                        TempData["Message"] = "Link Expired.";
                    }
                }
                else
                {
                    TempData["IsSuccess"] = false;
                    TempData["Message"] = "Invalid link.";
                }
            }
            else
            {
                TempData["IsSuccess"] = false;
                TempData["Message"] = "Invalid link.";
            }
            return View();
        }

        [HttpGet]
        public IActionResult SuccessRegistration()
        {
            return View();
        }
    }
}

Com.EzTender.PublicPortal/Controllers/RfqAccessByEmailController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Com.BudgetMetal.DataRepository.RfqInvites;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;

namespace Com.EzTender.PublicPortal.Controllers
{
    public class RfqAccessByEmailController : Controller
    {
        private readonly IRfqInvitesRepository repoRfqInvites;

        public RfqAccessByEmailController(IRfqInvitesRepository repoRfqInvites)
        {
            this.repoRfqInvites = repoRfqInvites;
        }

        // GET: RfqAccessByEmail
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<JsonResult> CheckRfqEmailandAccessCode(string Email, string AccessCode)
        {
            var result = await repoRfqInvites.GetRfqInvitesWithEmailandAccessCode(Email, AccessCode);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        // GET: RfqAccessByEmail/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: RfqAccessByEmail/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RfqAccessByEmail/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RfqAccessByEmail/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RfqAccessByEmail/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RfqAccessByEmail/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RfqAccessByEmail/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Com.EzTender.PublicPortal/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Com.BudgetMetal.Services.Company;
using Com.BudgetMetal.Services.RFQ;
using Com.BudgetMetal.ViewModels.Company;
using Configurations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;
using Newtonsoft.Json;

namespace Com.EzTender.PublicPortal.Controllers
{
    public class SuppliersController : Controller
    {
        private readonly ICompanyService svs;
        private readonly AppSettings _appSettings;
        private readonly IRFQService rfqService;

        public SuppliersController(ICompanyService svs, IOptions<AppSettings> appSettings, IRFQService rfqService)
        {
            this.svs = svs;
            this._appSettings = appSettings.Value;
            this.rfqService = rfqService;
        }

        
        public ActionResult PublicRfqByCompany(int id)
        {
            ViewBag.Company_Id = id;

            return View();
        }
        // GET: Suppliers
        public async Task<ActionResult> Index(string keyword, int page, int totalRecords)
        {
            var result = await svs.GetCompanySupplierList(keyword, page, _appSettings.TotalRecordPerPage);

            return View(result);
        }

        // GET: Suppliers/Details/5        
        public async Task<IActionResult> Details(int id)
        {
            VmCompanyItem item = await svs.GetCompanyById(id);

            if (item == null)
            {
                return NotFound();
            }
            return View(item);
        }

        // GET: Suppliers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Suppliers/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(IFormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Suppliers/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Suppliers/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: Suppliers/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Suppliers/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        [HttpGet]
        public async Task<JsonResult> GetSupplier(int page, string status, string Company_Id, string skeyword)
        {
            var result = await svs.GetCompanySupplierList(skeyword, page, 3);
            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }

        [HttpGet]
        public async Task<JsonResult> GetPublicRFQByCompany(int page, int Company_Id, string status, string skeyword)
        {
            //var company_Id = HttpContext.Session.GetString("Company_Id");
            var result = await rfqService.GetPublicRfqByCompany(page, Company_Id, 2, Convert.ToInt32(status),
                skeyword == null ? "" : skeyword);

            return new JsonResult(result, new JsonSerializerSettings()
            {
                ReferenceLoopHandling = ReferenceLoopHandling.Ignore
            });
        }
    }
}

Com.EzTender.PublicPortal/Views/Shared/_Default_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Com.GenericPlatform.WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/default/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/default/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/default/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/default/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Com.GenericPlatform.WebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Com.GenericPlatform.WebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/default/lib/jquery/dist/jquery.js"></script>
        <script src="~/default/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/default/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/default/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

Com.EzTender.PublicPortal/Views/Shared/_Empty_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>EzyTender - @ViewData["Title"]</title>
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Core Css -->
    <link href="~/material_theme/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Waves Effect Css -->
    <link href="~/material_theme/plugins/node-waves/waves.css" rel="stylesheet" />
    <!-- Animation Css -->
    <link href="~/material_theme/plugins/animate-css/animate.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="~/material_theme/css/style.css" rel="stylesheet">
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="~/material_theme/css/themes/all-themes.css" rel="stylesheet" />
</head>
<body class="login-page">
    @RenderBody()

    <!-- Jquery Core Js -->
    <script src="~/material_theme/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="~/material_theme/plugins/bootstrap/js/bootstrap.js"></script>
    <!-- Select Plugin Js -->
    <script src="~/material_theme/plugins/bootstrap-select/js/bootstrap-select.js"></script>
    
    @RenderSection("Scripts", required: false)
</body>
</html>

Com.EzTender.PublicPortal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <title>EzyTender - @ViewData["Title"]</title>
    <!-- Favicon-->
    <link rel="icon" href="favicon.ico" type="image/x-icon">
    <!-- Google Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Roboto:400,700&subset=latin,cyrillic-ext" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" type="text/css">
    <!-- Bootstrap Core Css -->
    <link href="~/material_theme/plugins/bootstrap/css/bootstrap.css" rel="stylesheet">
    <!-- Waves Effect Css -->
    <link href="~/material_theme/plugins/node-waves/waves.css" rel="stylesheet" />
    <!-- Animation Css -->
    <link href="~/material_theme/plugins/animate-css/animate.css" rel="stylesheet" />
    <!-- Morris Chart Css-->
    <link href="~/material_theme/plugins/morrisjs/morris.css" rel="stylesheet" />
    <!-- Bootstrap Material Datetime Picker Css -->
    <link href="~/material_theme/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet" />
    <!-- Custom Css -->
    <link href="~/material_theme/css/style.css" rel="stylesheet">
    <!-- AdminBSB Themes. You can choose a theme from css/themes instead of get all themes -->
    <link href="~/material_theme/css/themes/all-themes.css" rel="stylesheet" />
    <!-- Multi Select Css -->
    <link href="~/material_theme/plugins/multi-select/css/multi-select.css" rel="stylesheet">
    <!-- Bootstrap Select Css -->
    <link href="~/material_theme/plugins/bootstrap-select/css/bootstrap-select.css" rel="stylesheet" />
    <!-- Colorpicker Css -->
    <link href="~/material_theme/plugins/bootstrap-colorpicker/css/bootstrap-colorpicker.css" rel="stylesheet" />

    <!-- Jquery Core Js -->
    <script src="~/material_theme/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap Core Js -->
    <script src="~/material_theme/plugins/bootstrap/js/bootstrap.js"></script>


</head>
<body class="theme-red">
    <!-- Page Loader -->
    <div class="page-loader-wrapper">
        <div class="loader">
            <div class="preloader">
                <div class="spinner-layer pl-red">
                    <div class="circle-clipper left">
                        <div class="circle"></div>
                    </div>
                    <div class="circle-clipper right">
                        <div class="circle"></div>
                    </div>
                </div>
            </div>
            <p>Please wait...</p>
        </div>
    </div>
    <!-- #END# Page Loader -->
    <!-- Overlay For Sidebars -->
    <div class="overlay"></div>
    <!-- #END# Overlay For Sidebars -->
    <!-- Search Bar -->
    <div class="search-bar">
        <div class="search-icon">
            <i class="material-icons">search</i>
        </div>
        <input type="text" placeholder="START TYPING...">
        <div class="close-search">
            <i class="material-icons">close</i>
        </div>
    </div>
    <!-- #END# Search Bar -->
    <!-- Top Bar -->
    @await Html.PartialAsync("_PageHeader")
    <!-- #Top Bar -->
    @*<section>
            <!-- Left Sidebar -->
            <aside id="leftsidebar" class="sidebar">
                @await Html.PartialAsync("_Menu")
            </aside>
            <!-- #END# Left Sidebar -->
            <!-- Right Sidebar -->
        </section>*@
    <section class="content_middle" style="padding: 100px;">
        <div class="" style="Margin: auto; width: 80%;">
            @RenderBody()
        </div>
    </section>

    @await Html.PartialAsync("_ValidationScriptsPartial")



    <!-- Select Plugin Js -->
    <script src="~/material_theme/plugins/bootstrap-select/js/bootstrap-select.js"></script>
    <!-- Slimscroll Plugin Js -->
    <script src="~/material_theme/plugins/jquery-slimscroll/jquery.slimscroll.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="~/material_theme/plugins/node-waves/waves.js"></script>
    <!-- Jquery Validation Plugin Css -->
    <script src="~/material_theme/plugins/jquery-validation/jquery.validate.js"></script>
    <!-- JQuery Steps Plugin Js -->
    <script src="~/material_theme/plugins/jquery-steps/jquery.steps.js"></script>
    <!-- Sweet Alert Plugin Js -->
    <script src="~/material_theme/plugins/sweetalert/sweetalert.min.js"></script>
    <!-- Waves Effect Plugin Js -->
    <script src="~/material_theme/plugins/node-waves/waves.js"></script>



    <!-- Custom Js -->
    <script src="~/material_theme/js/admin.js"></script>


    <!-- Multi Select Plugin Js -->
    <script src="~/material_theme/plugins/multi-select/js/jquery.multi-select.js"></script>
    <!-- Demo Js -->
    <script src="~/material_theme/js/demo.js"></script>
  





</body>
</html>

Com.EzTender.PublicPortal/Views/Shared/_Menu.cshtml
<div class="menu">
    <ul class="list">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active">
            <a asp-area="" asp-controller="Home" asp-action="Index">
                <i class="material-icons">home</i>
                <span>Dashboard</span>
            </a>
        </li>
    </ul>
</div>
<!-- #Menu -->
<!-- Footer -->
<div class="legal">
    <div class="copyright">
        &copy; 2018 <a href="javascript:void(0);">Stylar Digital</a>.
    </div>
    <div class="version">
        <b>Version: </b> 1.0.5
    </div>
</div>
<!-- #Footer -->

Com.EzTender.PublicPortal/Views/Shared/_PageHeader.cshtml
<nav class="navbar">
    <div class="container-fluid">
        <div class="navbar-header">
            <a href="javascript:void(0);" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse" aria-expanded="false"></a>
            <a href="javascript:void(0);" class="bars"></a>
            <a class="navbar-brand" href='@Url.Action("Index","Home")'>EzyTender Public Portal</a>
            <a class="navbar-brand" href='@Url.Action("Index","Suppliers")'>Supplier Directory</a>
        </div>
        <div class="collapse navbar-collapse" id="navbar-collapse">
            <ul class="nav navbar-nav navbar-right">

                @*<li class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                <i class="material-icons">notifications</i>
                <span class="label-count">7</span>
            </a>
        </li>
        <!-- #END# Notifications -->
        <!-- Tasks -->
        <li class="dropdown">
            <a href="javascript:void(0);" class="dropdown-toggle" data-toggle="dropdown" role="button">
                About
            </a>
        </li>*@


                <!-- #END# Tasks -->
                <li class="pull-right"><a href='@Url.Action("Index","Registration")' class="js-right-sidebar" data-close="true">REGISTER</a></li>
                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true">FEEDBACK</a></li>
                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true">CONTACT US</a></li>
                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true">FAQ</a></li>
                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true">GETTING STARTED</a></li>
                <li class="pull-right"><a href="javascript:void(0);" class="js-right-sidebar" data-close="true">ABOUT US</a></li>
                <li class="pull-right"><a href='@Url.Action("Index","RfqAccessByEmail")' class="js-right-sidebar" data-close="true">Rfq Invites</a></li>

            </ul>
        </div>
    </div>
</nav>