Com.EazyTender_Admin/Controllers/ServiceTagsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Com.BudgetMetal.Services.ServiceTags;
using Com.BudgetMetal.ViewModels.ServiceTags;
using Com.EazyTender_Admin.Configurations;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Options;

namespace Com.EazyTender_Admin.Controllers
{
    public class ServiceTagsController : Controller
    {
        private readonly IServiceTagsService svs;
        private readonly AppSettings _appSettings;

        public ServiceTagsController(IServiceTagsService svs, IOptions<AppSettings> appSettings)
        {
            this.svs = svs;
            this._appSettings = appSettings.Value;
        }

        // GET: ServiceTags
        public async Task<ActionResult> Index(string keyword, int page, int totalRecords)
        {
            var result = await svs.GetServiceTagsByPage(keyword, page, _appSettings.TotalRecordPerPage);

            return View(result);
        }

        // GET: ServiceTags/Details/5
        public ActionResult Details(int id)
        {   
            return View();
        }

        // GET: ServiceTags/Create
        public async Task<ActionResult> Create()
        {
            var obj = await svs.GetFormObject();
            return View(obj);
        }

        // POST: ServiceTags/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VmServiceTagsItem serviceTagsItem)
        {
            var result = svs.Insert(serviceTagsItem);

            if (result.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(serviceTagsItem);
            }
        }

        // GET: ServiceTags/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            int _id = (int)id;

            VmServiceTagsItem rItem = await svs.GetServiceTagsById(_id);

            if (rItem == null)
            {
                return NotFound();
            }
            return View(rItem);

        }

        // POST: ServiceTags/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(int id, VmServiceTagsItem _serviceTags)
        {
            if (id != _serviceTags.Id)
            {
                return NotFound();
            }

            var result = await svs.Update(_serviceTags);

            if (result.IsSuccess)
            {
                return RedirectToAction(nameof(Index));
            }
            else
            {
                return View(_serviceTags);
            }
        }

        // GET: ServiceTags/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: ServiceTags/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Com.EazyTender_Admin/Views/ServiceTags/Create.cshtml
@model Com.BudgetMetal.ViewModels.ServiceTags.VmServiceTagsItem

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}

<div class="container-fluid">
    <h3>Create Service Tags</h3>
    <div class="card">
        <div class="row"></div>
        <div class="row clearfix">
            <div class="col-md-8">
                <form asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    @*<div class="form-line col-md-8">
                            <br />
                            <label asp-for="Id" class="control-label"></label>
                            <input asp-for="Id" class="form-control" />
                            <span asp-validation-for="Id" class="text-danger"></span>
                        </div>*@
                    <div class="form-line col-md-8">
                        <br />
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-line col-md-8">
                        <br />
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-line col-md-8">
                        <br />
                        <label asp-for="Industry_Id" class="control-label">Industry</label>
                        <select asp-for="Industry_Id" asp-items="@(new SelectList(Model.IndustryList, "Id", "Name"))" class="form-control">
                            <option>Please select one</option>
                        </select>
                        <span asp-validation-for="Industry_Id" class="text-danger"></span>
                    </div>
                    <input type="hidden" asp-for="CreatedBy" class="form-control" />
                    <div class="form-group col-md-6">
                        <br />
                        <input type="submit" value="Create" class="btn btn-info" />
                    </div>
                    <br />
                </form>
            </div>
        </div>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
    <br />
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<!-- Select Plugin Js -->
<script src="~/material_theme/plugins/bootstrap-select/js/bootstrap-select.js"></script>

<!-- Multi Select Plugin Js -->
<script src="~/material_theme/plugins/multi-select/js/jquery.multi-select.js"></script>

Com.EazyTender_Admin/Views/ServiceTags/Edit.cshtml
@model Com.BudgetMetal.ViewModels.ServiceTags.VmServiceTagsItem

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<div class="container-fluid">
    <h3>Edit Service Tags</h3>
    <div class="card">
        <div class="row"></div>
        <hr />
        <div class="row clearfix">
            <div class="col-md-8">
                <form asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-line col-md-8">
                        <br />
                        <label asp-for="Id" class="control-label"></label>
                        <input asp-for="Id" readonly="readonly" class="form-control" />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                    <div class="form-line col-md-8">
                        <br />
                        <label asp-for="Name" class="control-label"></label>
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="form-line col-md-8">
                        <br />
                        <label asp-for="Description" class="control-label"></label>
                        <input asp-for="Description" class="form-control" />
                        <span asp-validation-for="Description" class="text-danger"></span>
                    </div>
                    <div class="form-line col-md-8">
                        <br />
                        <label asp-for="Industry_Id" class="control-label">Code Category</label>
                        <select asp-for="Industry_Id" onchange="onFormSelected(this.value)" asp-items="@(new SelectList(Model.IndustryList, "Id", "Name", Model.Industry_Id))" class="form-control">
                            <option>Please select one</option>
                        </select>
                        <span asp-validation-for="Industry_Id" class="text-danger"></span>
                    </div>
                    <div class="form-group col-md-6">
                        <br />
                        <div class="checkbox">
                            <input type="checkbox" class="chk-col-red" asp-for="IsActive" />
                            <label for="IsActive"> Is Active</label>
                        </div>
                    </div>
                    <input type="hidden" asp-for="UpdatedBy" class="form-control" />
                    <div class="form-group col-md-8">
                        <br />
                        <input type="submit" value="Save" class="btn btn-info" />
                    </div>
                    <br />
                </form>
            </div>
        </div>
    </div>
    <div>
        <a asp-action="Index">Back to List</a>
    </div>
    <br />
</div>
@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}
<!-- Select Plugin Js -->
<script src="~/material_theme/plugins/bootstrap-select/js/bootstrap-select.js"></script>

<!-- Multi Select Plugin Js -->
<script src="~/material_theme/plugins/multi-select/js/jquery.multi-select.js"></script>

Com.EazyTender_Admin/Views/ServiceTags/Index.cshtml
@model Com.BudgetMetal.ViewModels.ServiceTags.VmServiceTagsPage

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout1.cshtml";
}
<h3>Service Tags</h3>
<div class="card">
    <div class="row"></div>
    <div class="header">
        <div class="row">
            @using (Html.BeginForm("Index", "ServiceTags", FormMethod.Get))
            {
                <div class="col-sm-5">
                    @Html.TextBox("keyword",
         null,
         new {
             id = "search_key",
             @class = "form-control"
         })
                </div>
                <div class="col-sm-1">
                    <input class="btn btn-info" type="submit" value="Search" />
                </div>
            }
        </div>
    </div>
    <br />
    <table class="table">
        <thead>
            <tr>
                <th>#</th>
                <th>
                    @Html.DisplayNameFor(model => model.Result.Records[0].Name)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Result.Records[0].Description)
                </th>
                <th>Industry</th>
                <th><a asp-action="Create">Create New</a></th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @{
                int counter = 1;
                foreach (var item in Model.Result.Records)
                {
                    <tr>
                        <td> @counter </td>
                        <td> @item.Name </td>
                        <td> @item.Description </td>
                        <td> @(item.Industry == null ? "" : item.Industry.Name)</td>
                        <td hidden="hidden"> @item.Id </td>
                        <td>
                            <a asp-action="Edit" asp-route-id="@item.Id">Edit</a>
                            @*<a asp-action="Details" asp-route-id="@item.Id">Details</a>*@
                            <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                        </td>
                    </tr>
                    counter++;
                }
            }
        </tbody>
    </table>
    <div class="row">
        <div class="col-sm-12">
            <div class="pagination pull-right" style="padding:10px;">
                @{
                    int currentPage = Model.Result.CurrentPage;
                    int totalPage = Model.Result.TotalPage;
                    int previousPage = Model.Result.PreviousPage;
                    int nextPage = Model.Result.NextPage;

                    int startPage = currentPage - 5;
                    int endPage = currentPage + 4;

                    if (startPage <= 0)
                    {
                        endPage -= (startPage - 1);
                        startPage = 1;
                    }
                    if (endPage > totalPage)
                    {
                        endPage = totalPage;
                        if (endPage > 10)
                        {
                            startPage = endPage - 9;
                        }
                    }

                    @if (endPage > 1)
                    {
                        <ul class="pagination">
                            @if (currentPage > 1)
                            {
                                <li>
                                    <a class='btn btn-md btn-primary' href="~/ServiceTags">First</a>
                                </li>
                                <li>
                                    <a class='btn btn-md btn-primary' href="?page=@(currentPage - 1)">Previous</a>
                                </li>
                            }

                            @for (int page = startPage; page <= endPage; page++)
                            {
                                <li class="@(page == currentPage ? "active" : "")">
                                    <a class='btn btn-md btn-primary' href="?page=@(page)"> @(page) </a>
                                </li>
                            }

                            @if (currentPage < totalPage)
                            {
                                <li>
                                    <a class='btn btn-md btn-primary' href="?page=@(currentPage + 1)">Next</a>
                                </li>
                                <li>
                                    <a class='btn btn-md btn-primary' href="?page=@(totalPage)">Last</a>
                                </li>
                            }
                        </ul>
                    }
                }
            </div>
        </div>
    </div>
</div>